"""monetization_entry_and_prizes

Revision ID: 0fd0ce01e2bb
Revises: 37229de97859
Create Date: 2026-07-20 08:38:59.057894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0fd0ce01e2bb'
down_revision: Union[str, Sequence[str], None] = '37229de97859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Postgres enum types must be created explicitly before add_column/create_table
    payout_status_enum = sa.Enum('open', 'pending', 'paid', 'disputed', name='payoutstatus')
    payout_status_enum.create(op.get_bind(), checkfirst=True)

    entry_payment_status_enum = sa.Enum('pending', 'paid', 'refund_pending', 'refunded', name='entrypaymentstatus')
    entry_payment_status_enum.create(op.get_bind(), checkfirst=True)

    payout_row_status_enum = sa.Enum('pending', 'sent', 'failed', name='payoutrowstatus')
    payout_row_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('payment_handle', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'refund_pending', 'refunded', name='entrypaymentstatus', create_type=False), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_ref')
    )
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('contestant_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'sent', 'failed', name='payoutrowstatus', create_type=False), server_default='pending', nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_fee_cents', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), server_default='MYR', nullable=False))
        batch_op.add_column(sa.Column('payout_status', postgresql.ENUM('open', 'pending', 'paid', 'disputed', name='payoutstatus', create_type=False), server_default='open', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.drop_column('payout_status')
        batch_op.drop_column('currency')
        batch_op.drop_column('entry_fee_cents')

    op.drop_table('payouts')
    op.drop_table('entries_payments')
    # ### end Alembic commands ###
