"""admin role, ban flag, audit log

Revision ID: 5fe46efe4686
Revises: 0efc9d0f17f8
Create Date: 2026-07-12 23:40:17.536775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe46efe4686'
down_revision: Union[str, Sequence[str], None] = '0efc9d0f17f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.add_column() does not create the associated Postgres ENUM type on
    # its own (unlike op.create_table, which does) — create it explicitly
    # first. No-op on SQLite, which has no native enum type.
    userrole_enum = sa.Enum('user', 'admin', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', userrole_enum, server_default='user', nullable=False))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
