"""contest participation protection

Revision ID: b0e3286f3d7f
Revises: e0e82b44b13d
Create Date: 2026-07-15 19:22:41.245093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e3286f3d7f'
down_revision: Union[str, Sequence[str], None] = 'e0e82b44b13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_email_domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('join_password_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contests', schema=None) as batch_op:
        batch_op.drop_column('join_password_hash')
        batch_op.drop_column('allowed_email_domain')

    # ### end Alembic commands ###
