"""registration email policy

Revision ID: e0e82b44b13d
Revises: 6f7ffa78806b
Create Date: 2026-07-13 19:11:18.283311

"""
import re
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e82b44b13d'
down_revision: Union[str, Sequence[str], None] = '6f7ffa78806b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Mirrors app/email_policy.py's TLD heuristic — kept independent (no app
# import) so this migration stays portable and self-contained.
_TLD_RE = re.compile(r"\.edu$|\.edu\.[a-z]{2,3}$|\.ac\.[a-z]{2,3}$")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('allow', 'deny', name='domainkind'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )

    # Postgres doesn't auto-create ENUM types for add_column the way it
    # does for create_table — create it explicitly first.
    report_type_enum = sa.Enum('contestant', 'domain_request', name='reporttype')
    report_type_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', report_type_enum, server_default='contestant', nullable=False))
        batch_op.add_column(sa.Column('requested_domain', sa.String(length=255), nullable=True))
        batch_op.alter_column('contestant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_email', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###

    # Grandfather existing accounts: flag any pre-existing user whose email
    # wouldn't pass the new TLD heuristic. Heuristic-only (no dataset/admin
    # list lookup) to keep this migration self-contained and portable.
    conn = op.get_bind()
    users_table = sa.table(
        'users',
        sa.column('id', sa.Integer),
        sa.column('email', sa.String),
        sa.column('legacy_email', sa.Boolean),
    )
    for user_id, email in conn.execute(sa.select(users_table.c.id, users_table.c.email)):
        domain = email.rsplit('@', 1)[-1].lower()
        if not _TLD_RE.search(domain):
            conn.execute(
                users_table.update()
                .where(users_table.c.id == user_id)
                .values(legacy_email=True)
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('legacy_email')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('contestant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('requested_domain')
        batch_op.drop_column('type')

    op.drop_table('email_domains')
    # ### end Alembic commands ###

    sa.Enum(name='reporttype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='domainkind').drop(op.get_bind(), checkfirst=True)
